### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by jbremer** [MerlijnWajer/tracy#33]
* `pid` and `syscall_number` should at all times be a `long` (can use either `pid_t` or `int` I guess.)
* Functions which take a constant string as parameter should have `const char *` as type, rather than `char *`.

**Comment by MerlijnWajer** [comment]
I'm going to close this - mostly because I don't believe const to be particularly useful. (Somewhat related: The plan9 compiler also completely ignores const, afaics)

I'll have a look at some types a bit later.
