### ISSUE TITLE
_llseek gets wrong arguments

### ISSUE THREAD

**Issue by M1cha** [MerlijnWajer/tracy#44]
The kernel receives a wrong last argument:
multiboot: child__llseek(17, 0, 0, 0xbe938ad0, 1) // tracy
sys_llseek(17, 0, 0, 0xbe938ad0, 1019892) // kernel

test: http://pastebin.com/2NFGs8Xn

**Comment by MerlijnWajer** [comment]
Going to merge the PR soon -- meanwhile closing the issue. :-)
